//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://microsoft.com/webservices/", IsNullable=false)]
public partial class Kundendaten {
    
    private KundendatenCustomer[] customerField;
    
    private KundendatenProdukte[] produkteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Customer")]
    public KundendatenCustomer[] Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Produkte")]
    public KundendatenProdukte[] Produkte {
        get {
            return this.produkteField;
        }
        set {
            this.produkteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenCustomer {
    
    private KundendatenCustomerInformationen informationenField;
    
    /// <remarks/>
    public KundendatenCustomerInformationen Informationen {
        get {
            return this.informationenField;
        }
        set {
            this.informationenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenCustomerInformationen {
    
    private string customerIdField;
    
    private string customerNameField;
    
    private KundendatenCustomerInformationenCustomerLocations[] customerLocationsField;
    
    private KundendatenCustomerInformationenCustomerCostCenter[] customerCostCenterField;
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerLocations")]
    public KundendatenCustomerInformationenCustomerLocations[] CustomerLocations {
        get {
            return this.customerLocationsField;
        }
        set {
            this.customerLocationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerCostCenter")]
    public KundendatenCustomerInformationenCustomerCostCenter[] CustomerCostCenter {
        get {
            return this.customerCostCenterField;
        }
        set {
            this.customerCostCenterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenCustomerInformationenCustomerLocations {
    
    private string locationIdField;
    
    private string locationNameField;
    
    /// <remarks/>
    public string LocationId {
        get {
            return this.locationIdField;
        }
        set {
            this.locationIdField = value;
        }
    }
    
    /// <remarks/>
    public string LocationName {
        get {
            return this.locationNameField;
        }
        set {
            this.locationNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenCustomerInformationenCustomerCostCenter {
    
    private string costCenterIdField;
    
    private string costCenterNameField;
    
    /// <remarks/>
    public string CostCenterId {
        get {
            return this.costCenterIdField;
        }
        set {
            this.costCenterIdField = value;
        }
    }
    
    /// <remarks/>
    public string CostCenterName {
        get {
            return this.costCenterNameField;
        }
        set {
            this.costCenterNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenProdukte {
    
    private KundendatenProdukteInformationen informationenField;
    
    /// <remarks/>
    public KundendatenProdukteInformationen Informationen {
        get {
            return this.informationenField;
        }
        set {
            this.informationenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class KundendatenProdukteInformationen {
    
    private string productIdField;
    
    private string productNameField;
    
    private string itemNumberField;
    
    /// <remarks/>
    public string ProductId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    public string ItemNumber {
        get {
            return this.itemNumberField;
        }
        set {
            this.itemNumberField = value;
        }
    }
}
