//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.5477
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://microsoft.com/webservices/", IsNullable=false)]
public partial class Deregistration {
    
    private DeregistrationAbmeldung[] abmeldungField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Abmeldung")]
    public DeregistrationAbmeldung[] Abmeldung {
        get {
            return this.abmeldungField;
        }
        set {
            this.abmeldungField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldung {
    
    private DeregistrationAbmeldungHeader headerField;
    
    private DeregistrationAbmeldungVehicle vehicleField;
    
    private DeregistrationAbmeldungCarOwnerAdress carOwnerAdressField;
    
    private DeregistrationAbmeldungCarOwnerContact carOwnerContactField;
    
    private DeregistrationAbmeldungBank bankField;
    
    private DeregistrationAbmeldungCarOwnerPersonal carOwnerPersonalField;
    
    private string freetextFieldField;
    
    /// <remarks/>
    public DeregistrationAbmeldungHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public DeregistrationAbmeldungVehicle Vehicle {
        get {
            return this.vehicleField;
        }
        set {
            this.vehicleField = value;
        }
    }
    
    /// <remarks/>
    public DeregistrationAbmeldungCarOwnerAdress CarOwnerAdress {
        get {
            return this.carOwnerAdressField;
        }
        set {
            this.carOwnerAdressField = value;
        }
    }
    
    /// <remarks/>
    public DeregistrationAbmeldungCarOwnerContact CarOwnerContact {
        get {
            return this.carOwnerContactField;
        }
        set {
            this.carOwnerContactField = value;
        }
    }
    
    /// <remarks/>
    public DeregistrationAbmeldungBank Bank {
        get {
            return this.bankField;
        }
        set {
            this.bankField = value;
        }
    }
    
    /// <remarks/>
    public DeregistrationAbmeldungCarOwnerPersonal CarOwnerPersonal {
        get {
            return this.carOwnerPersonalField;
        }
        set {
            this.carOwnerPersonalField = value;
        }
    }
    
    /// <remarks/>
    public string FreetextField {
        get {
            return this.freetextFieldField;
        }
        set {
            this.freetextFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungHeader {
    
    private string customerIdField;
    
    private string locationIdField;
    
    private DeregistrationAbmeldungHeaderItem[] productCostCenterListField;
    
    private string zulassungsstelleIdField;
    
    /// <remarks/>
    public string CustomerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    public string LocationId {
        get {
            return this.locationIdField;
        }
        set {
            this.locationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public DeregistrationAbmeldungHeaderItem[] ProductCostCenterList {
        get {
            return this.productCostCenterListField;
        }
        set {
            this.productCostCenterListField = value;
        }
    }
    
    /// <remarks/>
    public string ZulassungsstelleId {
        get {
            return this.zulassungsstelleIdField;
        }
        set {
            this.zulassungsstelleIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungHeaderItem {
    
    private string productIdField;
    
    private string costCenterIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CostCenterId {
        get {
            return this.costCenterIdField;
        }
        set {
            this.costCenterIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungVehicle {
    
    private string vINField;
    
    private string hSNField;
    
    private string tSNField;
    
    private string vehicleVariantField;
    
    private string eVBNumberField;
    
    private string licenceNumberField;
    
    private System.DateTime generalInspectionDateField;
    
    private string registrationDocumentNumberField;
    
    private string emissionCodeField;
    
    private System.DateTime registrationDateField;
    
    private string colorCodeField;
    
    /// <remarks/>
    public string VIN {
        get {
            return this.vINField;
        }
        set {
            this.vINField = value;
        }
    }
    
    /// <remarks/>
    public string HSN {
        get {
            return this.hSNField;
        }
        set {
            this.hSNField = value;
        }
    }
    
    /// <remarks/>
    public string TSN {
        get {
            return this.tSNField;
        }
        set {
            this.tSNField = value;
        }
    }
    
    /// <remarks/>
    public string VehicleVariant {
        get {
            return this.vehicleVariantField;
        }
        set {
            this.vehicleVariantField = value;
        }
    }
    
    /// <remarks/>
    public string eVBNumber {
        get {
            return this.eVBNumberField;
        }
        set {
            this.eVBNumberField = value;
        }
    }
    
    /// <remarks/>
    public string LicenceNumber {
        get {
            return this.licenceNumberField;
        }
        set {
            this.licenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime GeneralInspectionDate {
        get {
            return this.generalInspectionDateField;
        }
        set {
            this.generalInspectionDateField = value;
        }
    }
    
    /// <remarks/>
    public string RegistrationDocumentNumber {
        get {
            return this.registrationDocumentNumberField;
        }
        set {
            this.registrationDocumentNumberField = value;
        }
    }
    
    /// <remarks/>
    public string EmissionCode {
        get {
            return this.emissionCodeField;
        }
        set {
            this.emissionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime RegistrationDate {
        get {
            return this.registrationDateField;
        }
        set {
            this.registrationDateField = value;
        }
    }
    
    /// <remarks/>
    public string ColorCode {
        get {
            return this.colorCodeField;
        }
        set {
            this.colorCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungCarOwnerAdress {
    
    private string streetField;
    
    private string streetnumberField;
    
    private string zipcodeField;
    
    private string cityField;
    
    private string countryField;
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string Streetnumber {
        get {
            return this.streetnumberField;
        }
        set {
            this.streetnumberField = value;
        }
    }
    
    /// <remarks/>
    public string Zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungCarOwnerContact {
    
    private string phoneField;
    
    private string faxField;
    
    private string mobilePhoneField;
    
    private string emailField;
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string MobilePhone {
        get {
            return this.mobilePhoneField;
        }
        set {
            this.mobilePhoneField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungBank {
    
    private string carOwnerBankNameField;
    
    private string accountNumberField;
    
    private string bankCodeField;
    
    private string ibanField;
    
    private string bicField;
    
    /// <remarks/>
    public string CarOwnerBankName {
        get {
            return this.carOwnerBankNameField;
        }
        set {
            this.carOwnerBankNameField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string BankCode {
        get {
            return this.bankCodeField;
        }
        set {
            this.bankCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Iban {
        get {
            return this.ibanField;
        }
        set {
            this.ibanField = value;
        }
    }
    
    /// <remarks/>
    public string Bic {
        get {
            return this.bicField;
        }
        set {
            this.bicField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
public partial class DeregistrationAbmeldungCarOwnerPersonal {
    
    private string nameField;
    
    private string firstnameField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
}
