//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KVSWebApplication.PrintServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintServiceReference.IPrintService")]
    public interface IPrintService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintService/EmissionBadgePrint", ReplyAction="http://tempuri.org/IPrintService/EmissionBadgePrintResponse")]
        void EmissionBadgePrint(string licenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintService/EmissionBadgePrint", ReplyAction="http://tempuri.org/IPrintService/EmissionBadgePrintResponse")]
        System.Threading.Tasks.Task EmissionBadgePrintAsync(string licenceNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintServiceChannel : KVSWebApplication.PrintServiceReference.IPrintService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintServiceClient : System.ServiceModel.ClientBase<KVSWebApplication.PrintServiceReference.IPrintService>, KVSWebApplication.PrintServiceReference.IPrintService {
        
        public PrintServiceClient() {
        }
        
        public PrintServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EmissionBadgePrint(string licenceNumber) {
            base.Channel.EmissionBadgePrint(licenceNumber);
        }
        
        public System.Threading.Tasks.Task EmissionBadgePrintAsync(string licenceNumber) {
            return base.Channel.EmissionBadgePrintAsync(licenceNumber);
        }
    }
}
