//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PET.CAB {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class faultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultCodeField;
        
        private string faultStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultString {
            get {
                return this.faultStringField;
            }
            set {
                this.faultStringField = value;
                this.RaisePropertyChanged("faultString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cab.de/WSSchema", ConfigurationName="CAB.cabPrinterSOAP")]
    public interface cabPrinterSOAP {
        
        // CODEGEN: Generating message contract since the operation getPrinterStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="status", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="status", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.getPrinterStatusResponse getPrinterStatus(PET.CAB.getPrinterStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (listOfFormatsRequest) of message getlistOfFormatsRequest does not match the default value (getlistOfFormats)
        [System.ServiceModel.OperationContractAttribute(Action="formatlist", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="formatlist", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.getlistOfFormatsResponse getlistOfFormats(PET.CAB.getlistOfFormatsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (listOfObjectsRequest) of message getlistOfObjectsRequest does not match the default value (getlistOfObjects)
        [System.ServiceModel.OperationContractAttribute(Action="objectlist", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="objectlist", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.getlistOfObjectsResponse getlistOfObjects(PET.CAB.getlistOfObjectsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (listOfJobsRequest) of message getlistOfJobsRequest does not match the default value (getlistOfJobs)
        [System.ServiceModel.OperationContractAttribute(Action="joblist", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="joblist", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.getlistOfJobsResponse getlistOfJobs(PET.CAB.getlistOfJobsRequest request);
        
        // CODEGEN: Generating message contract since the operation loadFormat is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="loadformat", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="loadformat", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.loadFormatResponse loadFormat(PET.CAB.loadFormatRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (printFormatRequest) of message printFormatRequest does not match the default value (printFormat)
        [System.ServiceModel.OperationContractAttribute(Action="printformat", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PET.CAB.faultType), Action="printformat", Name="faultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PET.CAB.printFormatResponse printFormat(PET.CAB.printFormatRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrinterStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        public string statusRequest;
        
        public getPrinterStatusRequest() {
        }
        
        public getPrinterStatusRequest(string statusRequest) {
            this.statusRequest = statusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrinterStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        public string statusResponse;
        
        public getPrinterStatusResponse() {
        }
        
        public getPrinterStatusResponse(string statusResponse) {
            this.statusResponse = statusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class format : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfFormatsRequest", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfFormatsRequest {
        
        public getlistOfFormatsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfFormatsResponse", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfFormatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("format")]
        public PET.CAB.format[] format;
        
        public getlistOfFormatsResponse() {
        }
        
        public getlistOfFormatsResponse(PET.CAB.format[] format) {
            this.format = format;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class objectType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfObjectsRequest", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfObjectsRequest {
        
        public getlistOfObjectsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfObjectsResponse", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfObjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("fObject")]
        public PET.CAB.objectType[] fObject;
        
        public getlistOfObjectsResponse() {
        }
        
        public getlistOfObjectsResponse(PET.CAB.objectType[] fObject) {
            this.fObject = fObject;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private System.DateTime dateField;
        
        private System.DateTime timeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=2)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfJobsRequest", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfJobsRequest {
        
        public getlistOfJobsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listOfJobsResponse", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class getlistOfJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("job")]
        public PET.CAB.job[] job;
        
        public getlistOfJobsResponse() {
        }
        
        public getlistOfJobsResponse(PET.CAB.job[] job) {
            this.job = job;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class loadFormat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string genericField;
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string generic {
            get {
                return this.genericField;
            }
            set {
                this.genericField = value;
                this.RaisePropertyChanged("generic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loadFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loadFormatRequest", Namespace="http://www.cab.de/WSSchema", Order=0)]
        public string loadFormatRequest1;
        
        public loadFormatRequest() {
        }
        
        public loadFormatRequest(string loadFormatRequest1) {
            this.loadFormatRequest1 = loadFormatRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loadFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loadFormatResponse", Namespace="http://www.cab.de/WSSchema", Order=0)]
        public PET.CAB.loadFormat loadFormatResponse1;
        
        public loadFormatResponse() {
        }
        
        public loadFormatResponse(PET.CAB.loadFormat loadFormatResponse1) {
            this.loadFormatResponse1 = loadFormatResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cab.de/WSSchema")]
    public partial class objectTypePrint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="printFormatRequest", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class printFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fObject", IsNullable=false)]
        public PET.CAB.objectTypePrint[] objects;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=1)]
        public string jobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=2)]
        public int numbers;
        
        public printFormatRequest() {
        }
        
        public printFormatRequest(PET.CAB.objectTypePrint[] objects, string jobID, int numbers) {
            this.objects = objects;
            this.jobID = jobID;
            this.numbers = numbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="printFormatResponse", WrapperNamespace="http://www.cab.de/WSSchema", IsWrapped=true)]
    public partial class printFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=0)]
        public string generic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cab.de/WSSchema", Order=1)]
        public bool result;
        
        public printFormatResponse() {
        }
        
        public printFormatResponse(string generic, bool result) {
            this.generic = generic;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cabPrinterSOAPChannel : PET.CAB.cabPrinterSOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cabPrinterSOAPClient : System.ServiceModel.ClientBase<PET.CAB.cabPrinterSOAP>, PET.CAB.cabPrinterSOAP {
        
        public cabPrinterSOAPClient() {
        }
        
        public cabPrinterSOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cabPrinterSOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cabPrinterSOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cabPrinterSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.getPrinterStatusResponse PET.CAB.cabPrinterSOAP.getPrinterStatus(PET.CAB.getPrinterStatusRequest request) {
            return base.Channel.getPrinterStatus(request);
        }
        
        public string getPrinterStatus(string statusRequest) {
            PET.CAB.getPrinterStatusRequest inValue = new PET.CAB.getPrinterStatusRequest();
            inValue.statusRequest = statusRequest;
            PET.CAB.getPrinterStatusResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).getPrinterStatus(inValue);
            return retVal.statusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.getlistOfFormatsResponse PET.CAB.cabPrinterSOAP.getlistOfFormats(PET.CAB.getlistOfFormatsRequest request) {
            return base.Channel.getlistOfFormats(request);
        }
        
        public PET.CAB.format[] getlistOfFormats() {
            PET.CAB.getlistOfFormatsRequest inValue = new PET.CAB.getlistOfFormatsRequest();
            PET.CAB.getlistOfFormatsResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).getlistOfFormats(inValue);
            return retVal.format;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.getlistOfObjectsResponse PET.CAB.cabPrinterSOAP.getlistOfObjects(PET.CAB.getlistOfObjectsRequest request) {
            return base.Channel.getlistOfObjects(request);
        }
        
        public PET.CAB.objectType[] getlistOfObjects() {
            PET.CAB.getlistOfObjectsRequest inValue = new PET.CAB.getlistOfObjectsRequest();
            PET.CAB.getlistOfObjectsResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).getlistOfObjects(inValue);
            return retVal.fObject;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.getlistOfJobsResponse PET.CAB.cabPrinterSOAP.getlistOfJobs(PET.CAB.getlistOfJobsRequest request) {
            return base.Channel.getlistOfJobs(request);
        }
        
        public PET.CAB.job[] getlistOfJobs() {
            PET.CAB.getlistOfJobsRequest inValue = new PET.CAB.getlistOfJobsRequest();
            PET.CAB.getlistOfJobsResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).getlistOfJobs(inValue);
            return retVal.job;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.loadFormatResponse PET.CAB.cabPrinterSOAP.loadFormat(PET.CAB.loadFormatRequest request) {
            return base.Channel.loadFormat(request);
        }
        
        public PET.CAB.loadFormat loadFormat(string loadFormatRequest1) {
            PET.CAB.loadFormatRequest inValue = new PET.CAB.loadFormatRequest();
            inValue.loadFormatRequest1 = loadFormatRequest1;
            PET.CAB.loadFormatResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).loadFormat(inValue);
            return retVal.loadFormatResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PET.CAB.printFormatResponse PET.CAB.cabPrinterSOAP.printFormat(PET.CAB.printFormatRequest request) {
            return base.Channel.printFormat(request);
        }
        
        public string printFormat(PET.CAB.objectTypePrint[] objects, string jobID, int numbers, out bool result) {
            PET.CAB.printFormatRequest inValue = new PET.CAB.printFormatRequest();
            inValue.objects = objects;
            inValue.jobID = jobID;
            inValue.numbers = numbers;
            PET.CAB.printFormatResponse retVal = ((PET.CAB.cabPrinterSOAP)(this)).printFormat(inValue);
            result = retVal.result;
            return retVal.generic;
        }
    }
}
